### ISSUE TITLE
Android 12, camera feed isn't accessed

### ISSUE THREAD

**Issue by PeterKW** [Harishwarrior/pulse_rate_monitor#27]
I'm not managing to get any readings or turn on the flash. I'm not sure what other debugging information to give?

I've double checked permissions and it's got access to microphone as well as camera. 

https://apt.izzysoft.de/fdroid/index/apk/com.harish.prm

**Comment by Harishwarrior** [comment]
> I'm not managing to get any readings or turn on the flash. I'm not sure what other debugging information to give?
> 
> I've double checked permissions and it's got access to microphone as well as camera.
> 
> https://apt.izzysoft.de/fdroid/index/apk/com.harish.prm

Share error log here.

**Comment by PeterKW** [comment]
I'm not sure how to get an error log? It doesn't crash

**Comment by Harishwarrior** [comment]
> I'm not sure how to get an error log? It doesn't crash

Install the debug build from the releases section and take the logs using adb.

https://github.com/Harishwarrior/pulse_rate_monitor/releases/tag/release_2023-04-20_07-04-58

**Comment by Harishwarrior** [comment]
> I'm not managing to get any readings or turn on the flash. I'm not sure what other debugging information to give?
> 
> I've double checked permissions and it's got access to microphone as well as camera. 
> 
> https://apt.izzysoft.de/fdroid/index/apk/com.harish.prm

You have to tap the heart to start the reading.
