### ISSUE TITLE
Make project iOS ready

### ISSUE THREAD

**Issue by Harishwarrior** [Harishwarrior/pulse_rate_monitor#5]
Build and fix project for iOS.

**Comment by mufida1018** [comment]
I am willing to do this

**Comment by Harishwarrior** [comment]
> I am willing to do this

Assigned!

**Comment by Aryashakya** [comment]
I would like to work on this feature.

**Comment by Harishwarrior** [comment]
> I would like to work on this feature.

Assigned

**Comment by Aryashakya** [comment]
I have submitted a pull request #18 . Could you review it?

**Comment by Harishwarrior** [comment]
#5

**Comment by Harishwarrior** [comment]
#18
