### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by Harishwarrior** [Harishwarrior/pulse_rate_monitor#7]
Improve documentation, update readme(add new images)  and get hacktoberfest-accepted

**Comment by Vortex1806** [comment]
Heyy, I can work on this?
Im new to open source and would really love to work on this

**Comment by Harishwarrior** [comment]
> Heyy, I can work on this?
> Im new to open source and would really love to work on this
> 

Make sure to go though the project and create the documentation in readme.md file. 

Go though other famous repo for documentation samples.

**Comment by Vortex1806** [comment]
Okay Thank you

**Comment by Vortex1806** [comment]
<img width="1355" alt="Screenshot 2022-10-07 at 9 29 33 AM" src="https://user-images.githubusercontent.com/78277252/194465109-61f0bbfd-4582-4634-945a-6ad580ef5c56.png">

I am facing this error while starting this project could you help me out with this

**Comment by Harishwarrior** [comment]
> <img alt="Screenshot 2022-10-07 at 9 29 33 AM" width="1355" src="https://user-images.githubusercontent.com/78277252/194465109-61f0bbfd-4582-4634-945a-6ad580ef5c56.png">
> 
> I am facing this error while starting this project could you help me out with this

Make sure you are using latest flutter version.

**Comment by Harishwarrior** [comment]
@Vortex1806 Can you pull changes and try again?

**Comment by siddesh3101** [comment]
> <img alt="Screenshot 2022-10-07 at 9 29 33 AM" width="1355" src="https://user-images.githubusercontent.com/78277252/194465109-61f0bbfd-4582-4634-945a-6ad580ef5c56.png">
> 
> I am facing this error while starting this project could you help me out with this



> Add documentation, update readme(add new images) and get hacktoberfest-accepted

Hey is this issue still open?

**Comment by siddesh3101** [comment]
> Add documentation, update readme(add new images) and get hacktoberfest-accepted

Hey is this issue still open?

**Comment by Harishwarrior** [comment]
> > Add documentation, update readme(add new images) and get hacktoberfest-accepted
> 
> Hey is this issue still open?
> 

Assigned to you now

**Comment by siddesh3101** [comment]
> > > Add documentation, update readme(add new images) and get hacktoberfest-accepted
> > 
> > 
> > Hey is this issue still open?
> 
> Assigned to you now

ok let me run the project and I will let you know if there are any errors.

**Comment by mufida1018** [comment]
Hey,I would like to work on this

**Comment by Harishwarrior** [comment]
> Hey,I would like to work on this

Assigned

**Comment by mufida1018** [comment]
Please check

**Comment by Ritikkumar992** [comment]
If this issue is not done yet, then I would like to work on it. Please assign it to me.

**Comment by Harishwarrior** [comment]
> If this issue is not done yet, then I would like to work on it. Please assign it to me.

Remember typo fixes are not valid for hacktoberfest. The contribution must be a valid one. No need to assign. Just create a PR once done.
